config:
  target: "https://3tgc11z1n1.execute-api.eu-west-1.amazonaws.com"  # Change this to your target URL
  phases:
    - duration: 60
      arrivalRate: 5
      rampTo: 10
      name: "Warm up phase"
    - duration: 10
      arrivalRate: 10
      name: "Sustained load"
  defaults:
    headers:
      Content-Type: "application/json"
      User-Agent: "Artillery Load Test"

scenarios:
  - name: "Public content"
    weight: 3
    flow:
      - get:
          url: "/prod/point"
          expect:
            - statusCode: 200
